#!/usr/bin/env python3
# Copyright (c) 2026 Bruce Blay
# SPDX-License-Identifier: GPL-3.0-or-later
"""Write src/Samples.h: Rill Mallet's piano zones and the lab's one-shots.

The piano clips are copied verbatim from rill-mallet/src/Samples.h (VCSL,
CC0, already at 32 kHz). The one-shots are the real hand claps from
rill-sound/public/samples, resampled to 32 kHz with ffmpeg. See
rill-sound/public/licenses/samples.txt for their sources.
"""
import argparse
from pathlib import Path
import re
import subprocess

RATE = 32000
ONE_SHOTS = ['hand-clap-1.wav', 'hand-clap-2.wav']


def main():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--mallet', default=root.parent / 'rill-mallet', type=Path)
    parser.add_argument('--sound', default=root.parent / 'rill-sound', type=Path)
    args = parser.parse_args()

    source = (args.mallet / 'src/Samples.h').read_text()
    arrays = re.findall(r'static const int16_t (piano_(\d+))\[(\d+)\] PROGMEM = \{(.*?)\};', source, re.S)
    if not arrays:
        raise SystemExit('No piano zones found in Rill Mallet')

    out = ['// Copyright (c) 2026 Bruce Blay',
           '// SPDX-License-Identifier: GPL-3.0-or-later',
           '// Generated by tools/embed_samples.py -- do not hand-edit.',
           '//',
           "// Piano: Rill Mallet's zones (VCSL, CC0), one every few semitones.",
           '// One-shots: real hand claps (CC0), see rill-sound/public/licenses.',
           '// All 32 kHz mono, read from flash a sample at a time.',
           '#pragma once',
           '#include <cstdint>',
           '#ifndef PROGMEM',
           '#define PROGMEM',
           '#endif',
           'namespace samples {',
           'struct Zone { const int16_t* data; uint32_t length; uint8_t root; };',
           'struct Clip { const int16_t* data; uint32_t length; };']
    for name, _, length, body in arrays:
        out.append(f'static const int16_t {name}[{length}] PROGMEM = {{{body}}};')
    out.append('static const Zone piano[] = {')
    out += [f'  {{{name}, {length}, {root}}},' for name, root, length, _ in arrays]
    out.append('};')
    out.append(f'constexpr unsigned pianoCount = {len(arrays)};')

    clips = []
    for index, file in enumerate(ONE_SHOTS):
        pcm = subprocess.run(['ffmpeg', '-loglevel', 'error', '-i', str(args.sound / 'public/samples' / file),
                              '-ac', '1', '-ar', str(RATE), '-f', 's16le', '-'], check=True, capture_output=True).stdout
        values = [int.from_bytes(pcm[i:i + 2], 'little', signed=True) for i in range(0, len(pcm) - 1, 2)]
        name = f'one_shot_{index}'
        rows = [','.join(map(str, values[i:i + 32])) for i in range(0, len(values), 32)]
        out.append(f'// {file}')
        out.append(f'static const int16_t {name}[{len(values)}] PROGMEM = {{\n' + ',\n'.join(rows) + '};')
        clips.append((name, len(values)))
    out.append('static const Clip oneShots[] = {')
    out += [f'  {{{name}, {length}}},' for name, length in clips]
    out.append('};')
    out.append('}  // namespace samples')
    (root / 'src/Samples.h').write_text('\n'.join(out) + '\n')
    print(f'{len(arrays)} piano zones, {len(clips)} one-shots')


if __name__ == '__main__':
    main()
