// Copyright (c) 2026 Bruce Blay
// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/export_scores.mjs from rill-sound/src/lab/phase-scores.js.
// Do not hand-edit: change the lab's scores and export again.
#pragma once
#include "ScoreTypes.h"

namespace score {

inline constexpr int8_t notes[] = {
  69,76,79,74,72,76,69,74,79,76,72,74,60,60,-1,60,60,60,-1,60,-1,60,60,-1
};
inline constexpr uint16_t orders[] = {
  0,9,5,2,10,11,3,4,6,8,1,7,0,5,9,3,4,10,1,7
};
inline constexpr Pattern patterns[] = {
  {0,12,0,12},
  {12,12,12,8}
};
inline constexpr Stage stages[] = {
  {300.0,Mode::Play,true,0.0,0.0,false,1.0,false,false,0.0,0,"","",""},
  {4.0,Mode::Rest,false,0.0,0.0,false,1.0,false,false,0.0,0,"","",""},
  {8.0,Mode::Play,true,0.0,0.0,false,1.0,false,false,0.0,0,"Unison","",""},
  {16.0,Mode::Play,true,0.0,1.0,false,1.0,false,false,0.0,0,"Moving to +1","",""},
  {8.0,Mode::Play,true,1.0,1.0,false,1.0,false,false,0.0,0,"1 ahead","",""},
  {16.0,Mode::Play,true,1.0,2.0,false,1.0,false,false,0.0,0,"Moving to +2","",""},
  {8.0,Mode::Play,true,2.0,2.0,false,1.0,false,false,0.0,0,"2 ahead","",""},
  {16.0,Mode::Play,true,2.0,3.0,false,1.0,false,false,0.0,0,"Moving to +3","",""},
  {8.0,Mode::Play,true,3.0,3.0,false,1.0,false,false,0.0,0,"3 ahead","",""},
  {16.0,Mode::Play,true,3.0,4.0,false,1.0,false,false,0.0,0,"Moving to +4","",""},
  {8.0,Mode::Play,true,4.0,4.0,false,1.0,false,false,0.0,0,"4 ahead","",""},
  {16.0,Mode::Play,true,4.0,5.0,false,1.0,false,false,0.0,0,"Moving to +5","",""},
  {8.0,Mode::Play,true,5.0,5.0,false,1.0,false,false,0.0,0,"5 ahead","",""},
  {16.0,Mode::Play,true,5.0,6.0,false,1.0,false,false,0.0,0,"Moving to +6","",""},
  {8.0,Mode::Play,true,6.0,6.0,false,1.0,false,false,0.0,0,"6 ahead","",""},
  {16.0,Mode::Play,true,6.0,7.0,false,1.0,false,false,0.0,0,"Moving to +7","",""},
  {8.0,Mode::Play,true,7.0,7.0,false,1.0,false,false,0.0,0,"7 ahead","",""},
  {16.0,Mode::Play,true,7.0,8.0,false,1.0,false,false,0.0,0,"Moving to +8","",""},
  {8.0,Mode::Play,true,8.0,8.0,false,1.0,false,false,0.0,0,"8 ahead","",""},
  {16.0,Mode::Play,true,8.0,9.0,false,1.0,false,false,0.0,0,"Moving to +9","",""},
  {8.0,Mode::Play,true,9.0,9.0,false,1.0,false,false,0.0,0,"9 ahead","",""},
  {16.0,Mode::Play,true,9.0,10.0,false,1.0,false,false,0.0,0,"Moving to +10","",""},
  {8.0,Mode::Play,true,10.0,10.0,false,1.0,false,false,0.0,0,"10 ahead","",""},
  {16.0,Mode::Play,true,10.0,11.0,false,1.0,false,false,0.0,0,"Moving to +11","",""},
  {8.0,Mode::Play,true,11.0,11.0,false,1.0,false,false,0.0,0,"11 ahead","",""},
  {16.0,Mode::Play,true,11.0,12.0,false,1.0,false,false,0.0,0,"Moving to +12","",""},
  {8.0,Mode::Play,true,12.0,12.0,false,1.0,false,false,0.0,0,"Unison again","",""},
  {104.0,Mode::Play,true,0.0,0.0,false,1.0,false,false,0.0,1,"","",""},
  {8.0,Mode::Play,true,0.0,0.0,false,1.0,false,false,0.0,1,"Unison","",""},
  {8.0,Mode::Play,true,1.0,1.0,false,1.0,false,false,0.0,1,"Section 2 of 13 · 1 ahead","",""},
  {8.0,Mode::Play,true,2.0,2.0,false,1.0,false,false,0.0,1,"Section 3 of 13 · 2 ahead","",""},
  {8.0,Mode::Play,true,3.0,3.0,false,1.0,false,false,0.0,1,"Section 4 of 13 · 3 ahead","",""},
  {8.0,Mode::Play,true,4.0,4.0,false,1.0,false,false,0.0,1,"Section 5 of 13 · 4 ahead","",""},
  {8.0,Mode::Play,true,5.0,5.0,false,1.0,false,false,0.0,1,"Section 6 of 13 · 5 ahead","",""},
  {8.0,Mode::Play,true,6.0,6.0,false,1.0,false,false,0.0,1,"Section 7 of 13 · 6 ahead","",""},
  {8.0,Mode::Play,true,7.0,7.0,false,1.0,false,false,0.0,1,"Section 8 of 13 · 7 ahead","",""},
  {8.0,Mode::Play,true,8.0,8.0,false,1.0,false,false,0.0,1,"Section 9 of 13 · 8 ahead","",""},
  {8.0,Mode::Play,true,9.0,9.0,false,1.0,false,false,0.0,1,"Section 10 of 13 · 9 ahead","",""},
  {8.0,Mode::Play,true,10.0,10.0,false,1.0,false,false,0.0,1,"Section 11 of 13 · 10 ahead","",""},
  {8.0,Mode::Play,true,11.0,11.0,false,1.0,false,false,0.0,1,"Section 12 of 13 · 11 ahead","",""},
  {8.0,Mode::Play,true,12.0,12.0,false,1.0,false,false,0.0,1,"Unison again","",""}
};
inline constexpr Part parts[] = {
  {"Piano 1",Voice::Piano,-1,0,1.3,1.0,"",0,1},
  {"Piano 2",Voice::Piano,-1,0,1.3,1.0,"",1,26},
  {"Clap 1",Voice::Sample,0,0,1.2,1.0,"",27,1},
  {"Clap 2",Voice::Sample,1,0,1.2,1.0,"",28,13}
};
inline constexpr Section sections[] = {
};
inline constexpr Piece pieces[] = {
  {"Piano Phase","Steve Reich",100000,12,1,0,2,0,0},
  {"Clapping Music","Steve Reich",180000,12,1,2,2,0,0}
};
inline constexpr unsigned pieceCount = 2;

}  // namespace score
